### ISSUE TITLE
Avoid password prompt after login

### ISSUE THREAD

**Issue by inad9300** [elementary/pantheon-agent-polkit#35] opened 2018-09-21 19:42 UTC
If short after having passed the greeter you want to install a program, you are requested for your password again. It's really annoying. The amount of times GNU/Linux users are requested for their passwords it's crazy. elementary OS is greatly about user experience, and this would improve it enormously!

**Comment by arshubham** [comment] 2018-09-21 19:52
Possible duplicate of: https://github.com/elementary/appcenter/issues/465

**Comment by inad9300** [comment] 2018-09-21 20:16
You can have password prompts beyond AppCenter. But elementary/appcenter#465 would feel already like a significant improvement.

**Comment by danirabbit** [comment] 2024-05-09 21:09
This is a rather old issue, but these days you don't need a password to install apps so closing as fixed. If there's another case where you feel a password shouldn't be needed please feel free to open a new issue report for each specific case

**Closed by danirabbit** 2024-05-09 21:09 UTC
